#ifndef ENTITYMANAGEMENT_GLOBAL_H
#define ENTITYMANAGEMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ENTITYMANAGEMENT_LIBRARY)
#  define ENTITYMANAGEMENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ENTITYMANAGEMENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ENTITYMANAGEMENT_GLOBAL_H
