/******************************************************************
** THIS FILE AUTOMATICALLY GENERATED by languages_generator.py
** by andy from https://iso639-3.sil.org/code_tables/download_tables on 2019-06-28.
** Instead of manually editing this file, you probably want to
** manually edit languages_generator.py and regenerate this file.
******************************************************************/

INSERT INTO language_scope (id, scope, name)
VALUES
  ( 1, 'I', 'Individual     '),
  ( 2, 'M', 'Macro Language '),
  ( 3, 'S', 'Special        ')
;
