/******************************************************************
** THIS FILE AUTOMATICALLY GENERATED by languages_generator.py
** by andy from https://iso639-3.sil.org/code_tables/download_tables on 2019-06-09.
** Instead of manually editing this file, you probably want to
** manually edit languages_generator.py and regenerate this file.
******************************************************************/

INSERT INTO language_type (id, type, name)
VALUES
  ( 1, 'A', 'Ancient     '),
  ( 2, 'C', 'Constructed '),
  ( 3, 'E', 'Extinct     '),
  ( 4, 'H', 'Historical  '),
  ( 5, 'L', 'Living      '),
  ( 6, 'S', 'Special     ')
;
            